---

- name: "update client configuration"
  template:
    src: "ssh_config.j2"
    dest: "/etc/ssh/ssh_config"
    owner: "root"
    group: "root"
    mode: 0444

- name: "remove root ssh configuration"
  file:
    path: "/root/.ssh"
    state: absent
